#!/bin/bash
##
## Xubuntu: installation
##

#installation du français
sudo apt-get install language-pack-fr language-pack-fr-base
sudo apt-get install language-pack-xfce-fr
sudo apt-get install language-pack-xfce-fr-base
sudo apt-get install language-pack-gnome-fr
sudo apt-get install language-pack-gnome-fr-base
sudo apt-get install language-support-fr
sudo install mozilla-firefox-local-fr
sudo update-manager -c -d

#nautilus
sudo apt-get install nautilus

#emacs
sudo apt-get install emacs

#sublim
sudo add-apt-repository ppa:webupd8team/sublime-text-2
sudo apt-get update
sudo apt-get install sublime-text

#git
sudo apt-get install git
sudo apt-get install gitk
git config --global user.email "aqdtvz9@gmail.com"
git config --global user.name "Rainiugnas"
git config --global core.editor "emacs -nw"
git config --global push.default simple
echo "Default commit message change me in  ~/.gitmessage.txt" > ~/.gitmessage
git config --global commit.template ~/.gitmessage.txt
sudo apt-get install git-flow

#google
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update
sudo apt-get install google-chrome-stable

#rails
sudo apt-get install curl
\curl -L https://get.rvm.io | bash -s stable --rails

#redis
sudo apt-get install redis-server

#heroku
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

#gem
sudo apt-get install postgresql
sudo apt-get install libpq-dev
sudo apt-get install imagemagick
gem install pg

#markdown editor
sudo apt-get install retext

#debuger
sudo apt-get install valgrind

#cpp
sudo apt-get install libboost-all-dev
sudo apt-get install qt-sdk qttools5-dev qttools5-dev-tools
sudo apt-get install portaudio19-dev portaudio19-doc
sudo apt-get install opus-tools opus-tools-dbg

#racourci
xfconf-query --channel xfce4-keyboard-shortcuts --property "/commands/custom/F1" --create --type string --set "xfce4-terminal"
xfconf-query --channel xfce4-keyboard-shortcuts --property "/commands/custom/F2" --create --type string --set "google-chrome"

#lamp + phpmyadmin
sudo apt-get install apache2 php5 mysql-server libapache2-mod-php5 php5-mysql
sudo apt-get install phpmyadmin


#mise a jour des depot
sudo apt-get update
sudo apt-get upgrade


----------
acceder a config terminal xfce => xfconf-query

----------------------------------------------------------------------------------------

##
## à lancer de temps en temps
##

sudo apt-get update
sudo apt-get upgrade
sudo update-manager -c -d

----------------------------------------------------------------------------------------

##
## Xubuntu: conf
##

cd
alias ne="emacs -nw"
alias clean="rm -rf *~"
source /home/rainiugnas/.rvm/scripts/rvm
setxkbmap fr
